#!/usr/bin/env bash
set -e

if [ "$WARP_HOME" = "" ]; then
  WARP_HOME=$HOME/.warp
fi

unset RBENV_DIR
unset RBENV_HOOK_PATH
unset RBENV_ROOT

$WARP_HOME/client/ruby/install_ruby.sh
$WARP_HOME/client/ruby/install_gemset.sh